runtime: python
env: flex

runtime_config:
  python_version: 3

entrypoint: streamlit run app_main.py --server.port $PORT --server.enableCORS=false

automatic_scaling:
  max_num_instances: 1

# Or manual scaling as below:
# manual_scaling:
#   instances: 1